CREATE SEQUENCE s2
	START WITH 310
	INCREMENT BY 1;

CREATE OR REPLACE TRIGGER q4_trigger
BEFORE INSERT ON employee
FOR EACH ROW
	BEGIN
	:NEW.EMP_ID:=S2.NEXTVAL;
	END;
/

BEGIN
INSERT INTO EMPLOYEE (FNAME, LNAME, MANAGER_EMP_ID) VALUES('Panda', 'Bear', 304);
END;
/